RubinLab/epadjs

src/App.js, src/components/management/annotations/annotations.jsx, src/components/management/mainMenu.jsx, src/components/searchView/annotations.jsx, src/components/searchView/searchView.jsx, src/components/searchView/series.jsx, src/components/searchView/studies.jsx, src/components/searchView/subjects.jsx
- Deletion from management annotation menu
triggers update in SearchView
=> Fix updating searchView on aim delete

src/services/templateServices.js
templates interface should use projects/lite/templates to pull the data
=> modifies the template service to use the project url

src/components/aimEditor/aimHelper.js
Some old aims migrated don't have it
=> handles missing frame number and defaults to 1

src/components/searchView/annotationDownloadModal.jsx, src/components/searchView/searchView.jsx, src/services/annotationServices.js
=> Implement DICOM Segmentation download

src/components/aimEditor/aimEditor.jsx
this branch previously merged but added control save button depending on the aim editor form situation. in case there are required fields save button will not save.
=> control save action after checking aimeditor form validation

src/components/aimEditor/parseClass.js
if there are multiple shapes in the same annotation, next drawing needs to follow template shape condition.
=> same annotation next shape relation fixed

package-lock.json, package.json
fixes 1 low react spinner 1 high react scripts vulns
=> fixes 1 low react spinner 1 high react scripts vulns

src/components/display/displayView.jsx
=> fixes the maximize bug

src/components/annotationsList/annotationDock/aimEntityData.jsx
=> Fix missing Observation Characteristic in annotation

src/components/searchView/Report.jsx, src/components/searchView/recist.js
=> Fix opening Non-target aims from report

src/components/aimEditor/parseClass.js
try catch added for allowed terms cardinality in case the id is not in dom, nomorequestion equality check switched to string comparaison
=> removing empty space from labels for multi drop

src/components/management/templates/index.jsx, src/components/searchView/uploadModal.jsx
=> Fix selected projectid in upload modal

src/components/annotationsList/annotationDock/aimEntityData.jsx, src/components/annotationsList/annotationsList.css
-Add more control to rendering annotation labels
-Fix styling of the annotation links table
=> Fix right side bar issues

src/components/ToolMenu/Interpolation.jsx, src/components/ToolMenu/ToolMenu.jsx, src/cornerstone-tools/tools/FreehandRoiSculptorTool.js, src/ohif-segmentation-plugin/util/freehandInterpolate/generateInterpolationData.js, src/ohif-segmentation-plugin/util/freehandInterpolate/interpolate.js
doesn't set the sculpt tool active in each tool menu render to fix the sculpt bug
cleans code
=> doesn't set the sculpt tool active in each tool menu render

src/components/management/annotations/annotations.jsx, src/components/management/annotations/toolbar.jsx
=> Fix delete and open while all annotations selected

src/components/ToolMenu/ToolMenu.jsx
=> Fix activating tool shortcuts while typing in aim editor

src/components/management/projects/projectEditingForm.jsx
=> Fill input fields instead of placeholder

src/components/sideBar/sidebar.jsx
=> Add sanity check for templates without project assignment

src/components/flexView/StudyTable.jsx
=> Fix filter logic

src/components/annotationSearch/index.jsx
=> Fix infinite search call at pagination in Search

src/components/annotationSearch/index.jsx
=> Fix Regression of annotation page refresh after delete

src/components/ToolMenu/ToolMenu.jsx
=> Fix tool shortcuts

src/components/management/worklists/worklistCreationForm.jsx
=> Add explanation to Add Requirement button

src/constants.js
=> Add NM to modality list

src/components/display/SeriesDropDown.jsx, src/components/display/displayView.jsx
=> Reset page index when changing series

src/components/management/worklists/workLists.jsx, src/components/searchView/Series.jsx, src/components/searchView/Studies.jsx, src/components/searchView/searchView.jsx
=> Fix select-all in worklist

src/components/ToolMenu/ToolMenu.jsx
=> Fix having an active tool after selecting "Select" via shortcut

src/components/management/menuStyle.css, src/components/management/projects/projectCreationForm.jsx, src/components/management/worklists/worklistCreationForm.jsx
=> Fix styling of create project form

src/App.js
=> Initialize pid with encrypted data

src/App.js, src/components/RightsideBar/RightsideBar.jsx
=> Close right bar if thick and encypted

src/components/display/displayView.jsx
=> Fix refreshing page when press enter in slide no input

src/components/management/worklists/worklistCreationForm.jsx
=> Remove required Requirement at worklist creation

src/components/annotationsList/selectSerieModal.jsx, src/services/seriesServices.js
=> Save selection as significant seriers in Teaching only

src/components/management/common/alertDeletionModal.jsx, src/components/management/projects/projects.jsx
=> Call setState before async method

src/components/display/displayView.jsx
=> Fix falsy index by adding OR control

src/components/management/projects/projects.jsx
=> Add button for listing users and roles

package.json, src/components/sideBar/style.css
=> Re-arrange the styling of the left pane tabs

src/components/flexView/index.jsx
=> Fix update Study list after uploading study

src/components/management/users/index.jsx
=> Fix user role assignment in lite mode

src/components/annotationsList/selectSerieModal.jsx
=> Delete study relation on Discard

src/components/annotationsList/action.js
=> Fix missing url in action

src/components/annotationsList/reducer.js
=> Add control to reducer to cover multipple patient

src/components/annotationsList/annotationDock/annotation.jsx, src/components/annotationsList/annotationDock/calculationLabel.jsx
=> Hide some of the label info

src/App.js, src/services/seriesServices.js
=> Revert "Force getSeries when coming from Sectra on App level"
